title: Hello, world! I'm Jai Luthra
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jai Luthra # add your name
author-img: jailuthra.jpg # add your photo
about-author: CSE Junior at Indian Institute of Technology Mandi(B18061)
social-twitter: # add your Twitter handle
social-facebook: jailuthra.7701 # add your Facebook handle
social-github: JaiLuthra1 # add your Github handle
social-linkedin: jailuthra # add your Linkedin handle
social-email: luthrajaiji@gmail.com # add your Email address

# Disqus
discus-identifier: 

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
